spring:
  profiles:
    active: dev
  application:
    name: bwgServer
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    #data: classpath:sql/data.sql
    schema: classpath:sql/schema.sql
    #url: jdbc:h2:file:/home/h2/serverdb;AUTO_Server=TRUE;DB_CLOSE_DELAY=-1
    #url: jdbc:h2:file:D:\\h2\\quickstart;AUTO_Server=TRUE;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        security: debug