spring:
  profiles:
    active: dev
  application:
    name: bwgServer
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    #data: classpath:sql/data.sql
    schema: classpath:sql/schema.sql
    #url: jdbc:h2:file:/home/h2/serverdb;AUTO_Server=TRUE;DB_CLOSE_DELAY=-1
    #url: jdbc:h2:file:D:\\h2\\quickstart;AUTO_Server=TRUE;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  #thymeleaf end
  mail:
    host: smtp.163.com
    username: &username developall@163.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


#日志级别
logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        security: debug

#健康检查
management:
  endpoint:
    health:
      show-details: always

#免登陆路径
excludePath: /softs/**,/loginPage,/h2-console/**,/img/**

#权限
roles: "{ADMIN: '/actuator/**'}"

#发件服务器
mail:
  from: *username