CREATE TABLE IF NOT EXISTS BWG_SERVER_INFO (id bigint generated by default as identity,
ip varchar(50),port varchar(20),password varchar(50),pwd_Type varchar(20),primary key (id));

CREATE TABLE IF NOT EXISTS users (id bigint generated by default as identity,
username varchar(30),name varchar(30),password varchar(30),createDate datetime,
accessByMb varchar(1),accessByMail varchar(1)
);

CREATE TABLE IF NOT EXISTS User_Detail (id bigint generated by default as identity,
userNo bigint,mobile varchar(21),email varchar(21),createDate datetime
);